name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - changed-files
      - checks
      # - devcontainer
      - conda-python-build
      - conda-python-tests
      - wheel-build-nx-cugraph
      - wheel-tests-nx-cugraph
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@pure_wheels
    if: always()
    with:
      needs: ${{ toJSON(needs) }}
  changed-files:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/changed-files.yaml@pure_wheels
    with:
      files_yaml: |
        test_notebooks:
          - '**'
          - '!.devcontainer/**'
          - '!README.md'
          - '!ci/release/update-version.sh'
        test_python:
          - '**'
          - '!.devcontainer/**'
          - '!README.md'
          - '!ci/release/update-version.sh'
          - '!notebooks/**'
  # devcontainer:
  #   secrets: inherit
  #   uses: rapidsai/shared-workflows/.github/workflows/build-in-devcontainer.yaml@pure_wheels
  #   with:
  #     arch: '["amd64", "arm64"]'
  #     cuda: '["13.0"]'
  #     node_type: "cpu8"
  #     rapids-aux-secret-1: GIST_REPO_READ_ORG_GITHUB_TOKEN
  #     env: |
  #       SCCACHE_DIST_MAX_RETRIES=inf
  #       SCCACHE_SERVER_LOG=sccache=debug
  #       SCCACHE_DIST_FALLBACK_TO_LOCAL_COMPILE=false
  #       SCCACHE_DIST_AUTH_TOKEN_VAR=RAPIDS_AUX_SECRET_1
  #     build_command: |
  #       sccache --zero-stats;
  #       build-all -j0 --verbose 2>&1 | tee telemetry-artifacts/build.log;
  #       sccache --show-adv-stats | tee telemetry-artifacts/sccache-stats.txt;
  checks:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/checks.yaml@pure_wheels
    with:
      enable_check_generated_files: false
  conda-python-build:
    needs: [checks]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-build.yaml@pure_wheels
    with:
      build_type: pull-request
      script: ci/build_python.sh
      noarch: true
  conda-python-tests:
    needs: [conda-python-build, changed-files]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-tests.yaml@pure_wheels
    if: fromJSON(needs.changed-files.outputs.changed_file_groups).test_python
    with:
      build_type: pull-request
      run_codecov: false
      script: ci/test_python.sh
  wheel-build-nx-cugraph:
    needs: [checks]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@pure_wheels
    with:
      build_type: pull-request
      script: ci/build_wheel_nx-cugraph.sh
      package-name: nx-cugraph
      package-type: python
      pure-wheel: true
  wheel-tests-nx-cugraph:
    needs: [wheel-build-nx-cugraph, changed-files]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@pure_wheels
    if: fromJSON(needs.changed-files.outputs.changed_file_groups).test_python
    with:
      build_type: pull-request
      script: ci/test_wheel_nx-cugraph.sh
      # This selects "ARCH=amd64 + the latest supported Python, 1 job per major CUDA version".
      matrix_filter: map(select(.ARCH == "amd64")) | group_by(.CUDA_VER|split(".")|map(tonumber)|.[0]) | map(max_by([(.PY_VER|split(".")|map(tonumber)), (.CUDA_VER|split(".")|map(tonumber))]))
